### PR TITLE
Sort npm scripts by name

### PR DESCRIPTION
**Pull request by danez**
Not sure if this is something that you want but I ended up needing to search my commands in the list, because they are not sorted in package.json.
This way they would be sorted by name and are easier to find.

### CODE REVIEW

**Comment by stefanjudis** [comment]
yeah fine with me. :) thx.

**Comment by stefanjudis** [comment]
will push the next prerelease in a few days... but you can easily build it yourself if you wanna have it today.

Auto-updates are not there yet. ;)

**Comment by danez** [comment]
No problem, I'm already sold to forrest anyway 😝

**Comment by stefanjudis** [comment]
Nice - glad you like it! :)

You discovered key board navigations?
If you plan to contribute more I'd be happy to add you as a collab too. :)

https://github.com/stefanjudis/forrest#forrest-is-an-open-open-source-project

**Comment by danez** [comment]
Ah nice thing, didn't see the keyboard navigation before.

I might come back and make contributions, but my quota for maintaining projects is currently already pretty much reached with babel. I let you know when I change my mind.

**Comment by stefanjudis** [comment]
> but my quota for maintaining projects is currently already pretty much reached with babel

Ja I saw that! 🎉  Congrats!

**Pull request merged**
